/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vu.boot;

import java.util.HashMap;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Good bye World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }
}
